version: '3'
services:
  be2:
    image: python:3.9
    ports:
      - "8083:80"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.be2.rule=Host(`fe.com`) && PathPrefix(`/api/be2`)"
    environment:
      - TZ=Asia/Bangkok
    # deploy:
    #   mode: replicated
    #   replicas: 3
    networks:
      - proxy
networks:
  proxy:
    external: true
